build:
	gcc p1.c -o p1.o -Wall -lm
	gcc p2.c -o p2.o -Wall -lm
	gcc p3.c -o p3.o -Wall -lm
	gcc p4.c -o p4.o -Wall -lm
	gcc p5.c -o p5.o -Wall -lm
	gcc p6.c -o p6.o -Wall -lm
run:
	./Prob
clean:
	rm -rf p*.o